<?php

declare(strict_types=1);
/*
 * This file is part of the gpoehl/phpReport library.
 *
 * @license   GNU LGPL v3.0 - For details have a look at the LICENSE file
 * @copyright Günter Pöhl
 * @link      https://github.com/gpoehl/phpReport/readme
 * @author    Günter Pöhl  <phpReport@gmx.net>
 */

namespace gpoehl\phpReport;


/**
 * Prototype provides some basic output to help developing classes using phpReport.
 * Redirect target actions via RuntimeOption or call methods direct via
 * Report prototype().
 */
interface PrototypeInterface
{

    /**
     * @param Report $rep The php report object
     */
    public function __construct(Report $rep) ;

    

    /**
     * Call related method to the one last called in target class.
     * Parameters are pulled here to simplify the report class.
     * @return string Html table generated by method to be called
     */
    public function magic(): string ;
    


    public function Start(): string ;

    public function Finish(): string ;
   

    public function TotalHeader();

    public function TotalFooter(): string ;
    
    public function GroupBefore($val, $row, $rowKey): string ;

    public function GroupHeader($val, $row, $rowKey): string;

    /**
     * Prepare output for group footers
     * Note that $this->rep->dims->current has the dim which forced the group change.
     * The related dim to a group must be get out of the group object.
     * @param type $val
     * @param type $row
     * @param type $rowKey
     * @return string Table with data related to a group footer
     */
    public function GroupFooter($val, $row, $rowKey): string ;

    public function GroupAfter($val, $row, $rowKey): string ;

    public function DetailHeader($row, $rowKey): string ;

    public function Detail($row, $rowKey): string ;

    public function DetailFooter($row, $rowKey): string ;

    public function NoData(): string ;

    /**
     * Create output when no data was given in $dimID for next dimension
     * @param int $dimID The dimension id of row not having data for next dimension.
     * @return string Created output
     */
    public function dimNoData($row, $rowKey, int $dimID): string ;

    /**
     * Create output for row of dimensions but not for the last dimenion.
     * This is similar to the detail action for the last dimension.
     * @param type $row
     * @param type $rowKey
     * @param int $dimID The current dimension id
     * @return string Created output
     */
    public function dimDetail($row, $rowKey, int $dimID): string ;

    /**
     * Create output when row in dimensions didn't trigger a group change.
     * @param type $row
     * @param type $rowKey
     * @param int $dimID The current dimension id
     * @return string Created output
     */
    public function dimNoGroupChange($row, $rowKey, int $dimID): string ;

  

}
